SetPrivateProfileString('Multiplayer','Disable Banters','1')
SetPrivateProfileString('Multiplayer','Session Name','Enter Game Name')
SetPrivateProfileString('Multiplayer','Enable Chat Menu','1')
SetPrivateProfileString('Multiplayer','Player Name','Default Player')
SetPrivateProfileString('Multiplayer','Session Password','Enter Game Password')
SetPrivateProfileString('Bubbs Spell Menu Extended','Slots Area X','80')
SetPrivateProfileString('Bubbs Spell Menu Extended','Preferred Slot Size','52')
SetPrivateProfileString('Bubbs Spell Menu Extended','Slots Area W','1205')
SetPrivateProfileString('Bubbs Spell Menu Extended','Slots Area H','768')
SetPrivateProfileString('Bubbs Spell Menu Extended','Slots Area Y','0')
SetPrivateProfileString('Keymap Page','Wizard Spells','0')
SetPrivateProfileString('Program Options','Volume Voices','100')
SetPrivateProfileString('Program Options','Volume SFX','53')
SetPrivateProfileString('Program Options','Active Campaign','0')
SetPrivateProfileString('Program Options','Strref On','0')
SetPrivateProfileString('Program Options','Never Show Nuisance SOD','1')
SetPrivateProfileString('Program Options','Sprite Mirror','0')
SetPrivateProfileString('Program Options','Volume Ambients','12')
SetPrivateProfileString('Program Options','Volume Movie','56')
SetPrivateProfileString('Program Options','Disable Cosmetic Attacks','1')
SetPrivateProfileString('Program Options','Font Name','')
SetPrivateProfileString('Program Options','Disable Movies','0')
SetPrivateProfileString('Program Options','3D Acceleration','1')
SetPrivateProfileString('Program Options','Tooltips','43')
SetPrivateProfileString('Program Options','Volume Music','23')
SetPrivateProfileString('Program Options','UI Edit Mode','0')
SetPrivateProfileString('Program Options','Debug Mode','1')
SetPrivateProfileString('Program Options','Translucent Shadows','1')
SetPrivateProfileString('Program Options','Display Subtitles','1')
SetPrivateProfileString('Program Options','Drop Capitals','1')
SetPrivateProfileString('Program Options','Maximum Frame Rate','60')
SetPrivateProfileString('Program Options','Path Search Nodes','32000')
SetPrivateProfileString('Lua Edit','String3',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String1',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String6',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String9',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String5',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String7',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String4',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String8',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String0',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Lua Edit','String2',' C:CreateCreature("OGRE")')
SetPrivateProfileString('Language','Text','en_US')
SetPrivateProfileString('Keymap Miscellaneous','Rest','122')
SetPrivateProfileString('MOVIES','LOGO','1')
SetPrivateProfileString('MOVIES','RESTINN','1')
SetPrivateProfileString('MOVIES','SODCIN02','1')
SetPrivateProfileString('MOVIES','TAVERN','1')
SetPrivateProfileString('MOVIES','BGSUNRIS','1')
SetPrivateProfileString('MOVIES','SODCIN01','1')
SetPrivateProfileString('MOVIES','FRARMINN','1')
SetPrivateProfileString('MOVIES','ENDMOVIE','1')
SetPrivateProfileString('MOVIES','ENDCRDIT','1')
SetPrivateProfileString('MOVIES','INFELOGO','1')
SetPrivateProfileString('MOVIES','BWDRAGON','1')
SetPrivateProfileString('MOVIES','WOTC','1')
SetPrivateProfileString('MOVIES','SODCIN03','1')
SetPrivateProfileString('MOVIES','CREDITS','1')
SetPrivateProfileString('MOVIES','SEWER','1')
SetPrivateProfileString('MOVIES','BHAAL','1')
SetPrivateProfileString('MOVIES','BILOGO','1')
SetPrivateProfileString('MOVIES','GNOLL','1')
SetPrivateProfileString('MOVIES','RESTDUNG','1')
SetPrivateProfileString('MOVIES','DEATHAND','1')
SetPrivateProfileString('MOVIES','ELDRCITY','1')
SetPrivateProfileString('MOVIES','BLACKPIT','1')
SetPrivateProfileString('MOVIES','SODCIN05','1')
SetPrivateProfileString('MOVIES','PALACE','1')
SetPrivateProfileString('MOVIES','BGSUNSET','1')
SetPrivateProfileString('MOVIES','CAMP','1')
SetPrivateProfileString('MOVIES','IRONTHRN','1')
SetPrivateProfileString('MOVIES','MINEFLOD','1')
SetPrivateProfileString('MOVIES','NITEDAY','1')
SetPrivateProfileString('MOVIES','NASHKELL','1')
SetPrivateProfileString('MOVIES','TSRLOGO','1')
SetPrivateProfileString('MOVIES','CNDLKEEP','1')
SetPrivateProfileString('MOVIES','INTRO','1')
SetPrivateProfileString('MOVIES','BIOWBOTH','1')
SetPrivateProfileString('MOVIES','WYVERN','1')
SetPrivateProfileString('MOVIES','BEREGOST','1')
SetPrivateProfileString('MOVIES','LOGO_','1')
SetPrivateProfileString('MOVIES','DURLAG','1')
SetPrivateProfileString('MOVIES','DUNGEON','1')
SetPrivateProfileString('MOVIES','BGENTER','1')
SetPrivateProfileString('MOVIES','REST','1')
SetPrivateProfileString('MOVIES','DAYNITE','1')
SetPrivateProfileString('MOVIES','WRECK','1')
SetPrivateProfileString('MOVIES','BG4LOGO','1')
SetPrivateProfileString('WorldDialog','PortPosition','Left')
SetPrivateProfileString('WorldDialog','Position','0')
SetPrivateProfileString('Journal','Quest Filter','2')
SetPrivateProfileString('Fonts','ko_KR','NANUM')
SetPrivateProfileString('Fonts','uk_UA','PERMIAN')
SetPrivateProfileString('Fonts','ja_JP','MEIRYO')
SetPrivateProfileString('Fonts','ru_RU','PTSERIF')
SetPrivateProfileString('Fonts','zh_CN','SIMSUN')
SetPrivateProfileString('Fonts','Zoom','150')
SetPrivateProfileString('Game Options','RgFullBodyPortrait','1')
SetPrivateProfileString('Game Options','Difficulty Level','5')
SetPrivateProfileString('Game Options','Suppress Extra Difficulty Damage','1')
SetPrivateProfileString('Game Options','Auto Pause State','1153')
SetPrivateProfileString('Game Options','RgStoreMode','1')
SetPrivateProfileString('Game Options','QuicklootStartPreference','Visible')
SetPrivateProfileString('Game Options','Color Circles','0')
SetPrivateProfileString('Game Options','PWSFirstLoad','2.21')
SetPrivateProfileString('Game Options','RgHotkeyButton10','0,0,0,0')
SetPrivateProfileString('Game Options','Extra Feedback','0')
SetPrivateProfileString('Game Options','RgBestiaryKoef','1')
SetPrivateProfileString('Game Options','Show Learnable Spells','1')
SetPrivateProfileString('Game Options','Area Effects Density','100')
SetPrivateProfileString('Game Options','HP Over Head','0')
SetPrivateProfileString('Game Options','RgLargePortraits','0')
SetPrivateProfileString('Game Options','Journal Popups','1')
SetPrivateProfileString('Game Options','Command Sounds Frequency','2')
SetPrivateProfileString('Game Options','ShowMessageHistory','Off')
SetPrivateProfileString('Game Options','3E Thief Sneak Attack','0')
SetPrivateProfileString('Game Options','Last Save','000000000-[Edric Stormchant]-Auto-Save')
SetPrivateProfileString('Game Options','Disable Foot Steps During Combat','0')
SetPrivateProfileString('Game Options','Pausing Map','0')
SetPrivateProfileString('Game Options','RgHotkeyButton7','0,0,0,0')
SetPrivateProfileString('Game Options','Nightmare Bonus Gold','0')
SetPrivateProfileString('Game Options','RgHotkeyButton2','0,0,0,0')
SetPrivateProfileString('Game Options','Terrain Hugging','0')
SetPrivateProfileString('Game Options','MultiPortraitPicker','1')
SetPrivateProfileString('Game Options','Show AOE','1')
SetPrivateProfileString('Game Options','Bored Timeout','3000')
SetPrivateProfileString('Game Options','Enhanced Path Search','0')
SetPrivateProfileString('Game Options','RgInvPartyModeHover','0')
SetPrivateProfileString('Game Options','Locator Feedback Level','5')
SetPrivateProfileString('Game Options','Maximum HP','1')
SetPrivateProfileString('Game Options','RgHotkeyButton11','0,0,0,0')
SetPrivateProfileString('Game Options','Reverse Mouse Wheel Zoom','0')
SetPrivateProfileString('Game Options','Render Search Map','0')
SetPrivateProfileString('Game Options','Keyboard Scroll Speed','123')
SetPrivateProfileString('Game Options','RgQuicklootBottom','0')
SetPrivateProfileString('Game Options','RgMessUnlockedCoor','486,681,328,149')
SetPrivateProfileString('Game Options','RgHotkeyButton6','0,0,0,0')
SetPrivateProfileString('Game Options','Render Dynamic Search Map','0')
SetPrivateProfileString('Game Options','RgHotkeyButton12','0,0,0,0')
SetPrivateProfileString('Game Options','PermThief','0')
SetPrivateProfileString('Game Options','Force Dialog Pause','0')
SetPrivateProfileString('Game Options','Expire Trap Highlights','0')
SetPrivateProfileString('Game Options','Show Message Box Hint','0')
SetPrivateProfileString('Game Options','Mouse Scroll Speed','123')
SetPrivateProfileString('Game Options','No Difficulty Based XP Bonus','1')
SetPrivateProfileString('Game Options','RgQuicklootRows','3')
SetPrivateProfileString('Game Options','Tutorial State','1')
SetPrivateProfileString('Game Options','Footsteps','1')
SetPrivateProfileString('Game Options','Combat UI','1')
SetPrivateProfileString('Game Options','RgIsModernHud','1')
SetPrivateProfileString('Game Options','SelectedJournalSize','Large')
SetPrivateProfileString('Game Options','RgLoadColumns','3')
SetPrivateProfileString('Game Options','RgHotkeyButton4','0,0,0,0')
SetPrivateProfileString('Game Options','Show Character HP','1')
SetPrivateProfileString('Game Options','Always Dither','1')
SetPrivateProfileString('Game Options','Render Explored Map','1')
SetPrivateProfileString('Game Options','QuicklootENumber','Ten')
SetPrivateProfileString('Game Options','Over Confirm Everything','0')
SetPrivateProfileString('Game Options','RgSpaceAdvanceDialog','1')
SetPrivateProfileString('Game Options','Cleric Ranger Spells','1')
SetPrivateProfileString('Game Options','Attack Sounds','0')
SetPrivateProfileString('Game Options','Environmental Audio','1')
SetPrivateProfileString('Game Options','RgHotkeyButton5','0,0,0,0')
SetPrivateProfileString('Game Options','ClassicDialog','0')
SetPrivateProfileString('Game Options','Equipment Comparison','1')
SetPrivateProfileString('Game Options','Hotkeys On Tooltips','1')
SetPrivateProfileString('Game Options','All Learn Spell Info','0')
SetPrivateProfileString('Game Options','Auto Pause Center','1')
SetPrivateProfileString('Game Options','QuicklootMode','Expert')
SetPrivateProfileString('Game Options','RgUISkin','2')
SetPrivateProfileString('Game Options','Duplicate Floating Text','1')
SetPrivateProfileString('Game Options','GUI Feedback Level','6')
SetPrivateProfileString('Game Options','Render Travel Regions','0')
SetPrivateProfileString('Game Options','Heal Party on Rest','1')
SetPrivateProfileString('Game Options','RgHotkeyButton9','0,0,0,0')
SetPrivateProfileString('Game Options','Message Box Top','-69')
SetPrivateProfileString('Game Options','Ranged Weapon Switching','0')
SetPrivateProfileString('Game Options','Selection Sounds Frequency','2')
SetPrivateProfileString('Game Options','Nightmare Bonus XP','0')
SetPrivateProfileString('Game Options','Weather','1')
SetPrivateProfileString('Game Options','Last Save TBP','000000000-Auto-Save')
SetPrivateProfileString('Game Options','Extra Combat Info','0')
SetPrivateProfileString('Game Options','Tiles Precache Percent','100')
SetPrivateProfileString('Game Options','Filter Games','1')
SetPrivateProfileString('Game Options','RgRadarKey','a')
SetPrivateProfileString('Game Options','LargePortraits','1')
SetPrivateProfileString('Game Options','Last Save SOD','000000026-Interval-Save-2')
SetPrivateProfileString('Game Options','Infravision','1')
SetPrivateProfileString('Game Options','RgModernHudRight','1')
SetPrivateProfileString('Game Options','Render Actions','0')
SetPrivateProfileString('Game Options','Show Date On Pause','0')
SetPrivateProfileString('Game Options','RgQuicklootFilterJunk','0')
SetPrivateProfileString('Game Options','RgHotkeyButton8','0,0,0,0')
SetPrivateProfileString('Game Options','RgHotkeyButton1','0,0,0,0')
SetPrivateProfileString('Game Options','RgHotkeyButton3','0,0,0,0')
SetPrivateProfileString('Game Options','Subtitles','1')
SetPrivateProfileString('Game Options','RgHotkeyButtonsVisibility','0')
SetPrivateProfileString('Game Options','RgInventoryMode','0')
SetPrivateProfileString('Game Options','Disable Space Key In Conversations','0')
SetPrivateProfileString('Game Options','Classic Selection Circles','1')
SetPrivateProfileString('Game Options','RgLoadSort','0')
SetPrivateProfileString('Game Options','RgMessageboxUnlocked','1')
SetPrivateProfileString('Game Options','Quick Item Mapping','1')
SetPrivateProfileString('Game Options','RgRadarShowPcEffects','1')
SetPrivateProfileString('Game Options','Confirm Dialog','0')
SetPrivateProfileString('Game Options','RgQuicklootCenter','1')
SetPrivateProfileString('Game Options','Memory Level','1')
SetPrivateProfileString('Game Options','Critical Hit Screen Shake','1')
SetPrivateProfileString('Game Options','Show Triggers On Tab','1')
SetPrivateProfileString('Game Options','Enable Fog','0')
SetPrivateProfileString('Game Options','Effect Text Level','63')
SetPrivateProfileString('Window','Maximized','0')
SetPrivateProfileString('Window','h','768')
SetPrivateProfileString('Window','x','277')
SetPrivateProfileString('Window','Full Screen','1')
SetPrivateProfileString('Window','w','1366')
SetPrivateProfileString('Window','y','168')
SetPrivateProfileString('Script','IntervalSaveCombat','0')
SetPrivateProfileString('Script','scs_chaotic_commands','99')
SetPrivateProfileString('Script','scs_ranged','102')
SetPrivateProfileString('Script','IntervalSaveEnabled','1')
SetPrivateProfileString('Script','scs_pro_evil','122')
SetPrivateProfileString('Script','scs_death_ward','118')
SetPrivateProfileString('Script','scs_toggle_melee','107')
SetPrivateProfileString('Script','scs_melee','100')
SetPrivateProfileString('Script','scs_pro_elements','98')
SetPrivateProfileString('EEex','Uncap FPS Busy Wait Threshold','1')
SetPrivateProfileString('EEex','Effect Menu Module: Row Count','4')
SetPrivateProfileString('EEex','Time Step Module: Keybind','D|Down')
SetPrivateProfileString('EEex','Open Options Keybind','%92|Up')
SetPrivateProfileString('EEex','Scale Module: Percentage','0.8')
SetPrivateProfileString('EEex','Uncap FPS Limit','111')
SetPrivateProfileString('EEex','Toggle Keycode Output','`|Up')
SetPrivateProfileString('EEex','Timer Module: Hug Portraits','1')
SetPrivateProfileString('EEex','Timer Module: Show Modal','1')
SetPrivateProfileString('EEex','Timer Module: Show Contingency','1')
SetPrivateProfileString('EEex','Timer Module: Show Cast','1')
SetPrivateProfileString('EEex','Remove Middle Mouse Scroll Multiplier','1')
SetPrivateProfileString('EEex','Effect Menu Module: Launch Keybind','Left Shift|Down')
SetPrivateProfileString('EEex','Uncap FPS','1')
SetPrivateProfileString('Graphics','Use Character Highlights','1')
SetPrivateProfileString('Graphics','vendor','ATI Technologies Inc.')
SetPrivateProfileString('Graphics','Hardware Mouse Cursor','1')
SetPrivateProfileString('Graphics','RgSettingEEexZoomUI','8')
SetPrivateProfileString('Graphics','Zoom Lock','0')
SetPrivateProfileString('Graphics','Use Sprite Outlines','0')
SetPrivateProfileString('Graphics','renderer','AMD Radeon RX 9070 XT')
SetPrivateProfileString('Graphics','Area Map Zoom','0')
SetPrivateProfileString('Graphics','Use Nearest Neighbour Scaling','1')
SetPrivateProfileString('Graphics','version','OpenGL version 4.6.0 Compatibility Profile Context 26.2.2.260209 - build XXXX')
SetPrivateProfileString('Graphics','Scale UI','1')
SetPrivateProfileString('Graphics','Backend','0')
SetPrivateProfileString('Graphics','Greyscale On Pause','0')
SetPrivateProfileString('Graphics','Show Black Space','1')
